## Preprocessing

In [3]:
 # Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'
application_df = application_df.drop(columns=['EIN', 'NAME'])

# Verify the DataFrame after dropping the columns
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
# Determine the number of unique values in each column.
unique_counts = application_df.nunique()

# Display the unique value counts for each column.
print(unique_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
cutoff_value = 550
# use the variable name `application_types_to_replace`
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_gt1 = classification_counts[classification_counts > 1]
print(classification_counts_gt1)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
cutoff_value_classification = 100

# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts < cutoff_value_classification].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [11]:
# Convert categorical data to numeric with pd.get_dummies
application_df_encoded = pd.get_dummies(application_df)

In [12]:
# Split our preprocessed data into our features and target arrays
# Extract target variable
# Extract features and target
X = application_df_encoded.drop('IS_SUCCESSFUL', axis=1)
y = application_df_encoded['IS_SUCCESSFUL']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, input_dim=len(X_train.columns), activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

WARNING:tensorflow:From C:\Users\rontr\anaconda3\envs\dev\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3920

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 6381 (24.93 KB)
Trainable params: 6381 (24.93 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

WARNING:tensorflow:From C:\Users\rontr\anaconda3\envs\dev\lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [16]:
# Train the model with validation data
fit_model = nn.fit(X_train_scaled, y_train, epochs=100, validation_data=(X_test_scaled, y_test))

Epoch 1/100
WARNING:tensorflow:From C:\Users\rontr\anaconda3\envs\dev\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From C:\Users\rontr\anaconda3\envs\dev\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

804/804 [==============================] - 4s 4ms/step - loss: 0.5695 - accuracy: 0.7215 - val_loss: 0.5624 - val_accuracy: 0.7212
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5529 - accuracy: 0.7313 - val_loss: 0.5553 - val_accuracy: 0.7226
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5491 - accuracy: 0.7324 - val_loss: 0.5586 - val_accuracy: 0.7216
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5474 - accuracy: 0.7328 - val_loss: 0.5559 - val_accuracy: 0.7198
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5461 - accuracy: 0.7336 - val_loss: 0.5551 - val_accuracy: 0.7233
Epoch 6/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5456 - accuracy: 0.7344 - val_loss: 0.5543 - val_accuracy: 0.7247
Epoch 7/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5445 - accuracy: 0.7358 - val_loss: 0.5545 - val_accuracy: 0.7222
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7352 - val_loss: 0.5532 - val_accuracy: 0.7223
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7348 - val_loss: 0.5546 - val_accuracy: 0.7229
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7358 - val_loss: 0.5571 - val_accuracy: 0.7219
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5424 - accuracy: 0.7355 - val_loss: 0.5534 - val_accuracy: 0.7262
Epoch 12/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7365 - val_loss: 0.5537 - val_accuracy: 0.7245
Epoch 13/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5410 - accuracy: 0.7365 - val_loss: 0.5580 - val_accuracy: 0.7227
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5413 - accuracy: 0.7364 - val_loss: 0.5510 - val_accuracy: 0.7262
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7381 - val_loss: 0.5537 - val_accuracy: 0.7250
Epoch 16/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5404 - accuracy: 0.7368 - val_loss: 0.5525 - val_accuracy: 0.7223
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5400 - accuracy: 0.7374 - val_loss: 0.5541 - val_accuracy: 0.7240
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5399 - accuracy: 0.7378 - val_loss: 0.5522 - val_accuracy: 0.7235
Epoch 19/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5391 - accuracy: 0.7379 - val_loss: 0.5553 - val_accuracy: 0.7261
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5391 - accuracy: 0.7379 - val_loss: 0.5542 - val_accuracy: 0.7254
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5383 - accuracy: 0.7387 - val_loss: 0.5524 - val_accuracy: 0.7249
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5390 - accuracy: 0.7385 - val_loss: 0.5539 - val_accuracy: 0.7250
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7386 - val_loss: 0.5521 - val_accuracy: 0.7249
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7388 - val_loss: 0.5534 - val_accuracy: 0.7252
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5379 - accuracy: 0.7390 - val_loss: 0.5519 - val_accuracy: 0.7250
Epoch 26/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5381 - accuracy: 0.7391 - val_loss: 0.5528 - val_accuracy: 0.7237
Epoch 27/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5372 - accuracy: 0.7391 - val_loss: 0.5518 - val_accuracy: 0.7250
Epoch 28/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7390 - val_loss: 0.5521 - val_accuracy: 0.7252
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.7402 - val_loss: 0.5567 - val_accuracy: 0.7254
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7388 - val_loss: 0.5522 - val_accuracy: 0.7247
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7400 - val_loss: 0.5522 - val_accuracy: 0.7250
Epoch 32/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5363 - accuracy: 0.7396 - val_loss: 0.5555 - val_accuracy: 0.7241
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7399 - val_loss: 0.5541 - val_accuracy: 0.7269
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7394 - val_loss: 0.5574 - val_accuracy: 0.7250
Epoch 35/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5360 - accuracy: 0.7392 - val_loss: 0.5551 - val_accuracy: 0.7228
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7401 - val_loss: 0.5539 - val_accuracy: 0.7243
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7405 - val_loss: 0.5530 - val_accuracy: 0.7242
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7398 - val_loss: 0.5536 - val_accuracy: 0.7240
Epoch 39/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5357 - accuracy: 0.7410 - val_loss: 0.5541 - val_accuracy: 0.7248
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7405 - val_loss: 0.5554 - val_accuracy: 0.7252
Epoch 41/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5351 - accuracy: 0.7404 - val_loss: 0.5522 - val_accuracy: 0.7235
Epoch 42/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5351 - accuracy: 0.7405 - val_loss: 0.5550 - val_accuracy: 0.7236
Epoch 43/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5352 - accuracy: 0.7404 - val_loss: 0.5541 - val_accuracy: 0.7252
Epoch 44/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5347 - accuracy: 0.7411 - val_loss: 0.5544 - val_accuracy: 0.7231
Epoch 45/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5348 - accuracy: 0.7412 - val_loss: 0.5546 - val_accuracy: 0.7249
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5345 - accuracy: 0.7404 - val_loss: 0.5541 - val_accuracy: 0.7241
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5343 - accuracy: 0.7402 - val_loss: 0.5537 - val_accuracy: 0.7255
Epoch 48/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5347 - accuracy: 0.7416 - val_loss: 0.5551 - val_accuracy: 0.7249
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5345 - accuracy: 0.7397 - val_loss: 0.5548 - val_accuracy: 0.7247
Epoch 50/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5341 - accuracy: 0.7405 - val_loss: 0.5560 - val_accuracy: 0.7237
Epoch 51/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5343 - accuracy: 0.7402 - val_loss: 0.5549 - val_accuracy: 0.7247
Epoch 52/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5342 - accuracy: 0.7408 - val_loss: 0.5545 - val_accuracy: 0.7241
Epoch 53/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5338 - accuracy: 0.7414 - val_loss: 0.5559 - val_accuracy: 0.7240
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5341 - accuracy: 0.7402 - val_loss: 0.5552 - val_accuracy: 0.7248
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5336 - accuracy: 0.7401 - val_loss: 0.5563 - val_accuracy: 0.7242
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7409 - val_loss: 0.5553 - val_accuracy: 0.7242
Epoch 57/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5337 - accuracy: 0.7408 - val_loss: 0.5565 - val_accuracy: 0.7228
Epoch 58/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5334 - accuracy: 0.7411 - val_loss: 0.5554 - val_accuracy: 0.7238
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5342 - accuracy: 0.7414 - val_loss: 0.5549 - val_accuracy: 0.7256
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7417 - val_loss: 0.5558 - val_accuracy: 0.7231
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5338 - accuracy: 0.7407 - val_loss: 0.5549 - val_accuracy: 0.7237
Epoch 62/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5332 - accuracy: 0.7407 - val_loss: 0.5561 - val_accuracy: 0.7231
Epoch 63/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5327 - accuracy: 0.7406 - val_loss: 0.5571 - val_accuracy: 0.7236
Epoch 64/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5327 - accuracy: 0.7415 - val_loss: 0.5585 - val_accuracy: 0.7251
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5330 - accuracy: 0.7417 - val_loss: 0.5548 - val_accuracy: 0.7252
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5330 - accuracy: 0.7416 - val_loss: 0.5549 - val_accuracy: 0.7248
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5323 - accuracy: 0.7420 - val_loss: 0.5565 - val_accuracy: 0.7247
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5327 - accuracy: 0.7413 - val_loss: 0.5564 - val_accuracy: 0.7238
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5329 - accuracy: 0.7422 - val_loss: 0.5562 - val_accuracy: 0.7249
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5323 - accuracy: 0.7408 - val_loss: 0.5555 - val_accuracy: 0.7236
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5322 - accuracy: 0.7413 - val_loss: 0.5589 - val_accuracy: 0.7233
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5323 - accuracy: 0.7418 - val_loss: 0.5557 - val_accuracy: 0.7252
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5324 - accuracy: 0.7407 - val_loss: 0.5593 - val_accuracy: 0.7240
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.7420 - val_loss: 0.5586 - val_accuracy: 0.7250
Epoch 75/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5319 - accuracy: 0.7404 - val_loss: 0.5606 - val_accuracy: 0.7251
Epoch 76/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5325 - accuracy: 0.7412 - val_loss: 0.5587 - val_accuracy: 0.7240
Epoch 77/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5319 - accuracy: 0.7414 - val_loss: 0.5595 - val_accuracy: 0.7250
Epoch 78/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5321 - accuracy: 0.7415 - val_loss: 0.5575 - val_accuracy: 0.7251
Epoch 79/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5317 - accuracy: 0.7414 - val_loss: 0.5584 - val_accuracy: 0.7254
Epoch 80/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5322 - accuracy: 0.7416 - val_loss: 0.5603 - val_accuracy: 0.7241
Epoch 81/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5316 - accuracy: 0.7422 - val_loss: 0.5579 - val_accuracy: 0.7244
Epoch 82/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5320 - accuracy: 0.7423 - val_loss: 0.5578 - val_accuracy: 0.7249
Epoch 83/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5316 - accuracy: 0.7411 - val_loss: 0.5578 - val_accuracy: 0.7245
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5312 - accuracy: 0.7418 - val_loss: 0.5617 - val_accuracy: 0.7237
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5322 - accuracy: 0.7414 - val_loss: 0.5589 - val_accuracy: 0.7249
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5317 - accuracy: 0.7425 - val_loss: 0.5618 - val_accuracy: 0.7233
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5311 - accuracy: 0.7419 - val_loss: 0.5604 - val_accuracy: 0.7249
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.7420 - val_loss: 0.5572 - val_accuracy: 0.7257
Epoch 89/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5316 - accuracy: 0.7411 - val_loss: 0.5594 - val_accuracy: 0.7247
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5313 - accuracy: 0.7420 - val_loss: 0.5585 - val_accuracy: 0.7251
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7422 - val_loss: 0.5592 - val_accuracy: 0.7251
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7425 - val_loss: 0.5576 - val_accuracy: 0.7250
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5310 - accuracy: 0.7411 - val_loss: 0.5582 - val_accuracy: 0.7236
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5311 - accuracy: 0.7424 - val_loss: 0.5598 - val_accuracy: 0.7249
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5313 - accuracy: 0.7423 - val_loss: 0.5624 - val_accuracy: 0.7248
Epoch 96/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5309 - accuracy: 0.7416 - val_loss: 0.5606 - val_accuracy: 0.7255
Epoch 97/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5314 - accuracy: 0.7423 - val_loss: 0.5582 - val_accuracy: 0.7245
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5306 - accuracy: 0.7419 - val_loss: 0.5602 - val_accuracy: 0.7255
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5309 - accuracy: 0.7425 - val_loss: 0.5607 - val_accuracy: 0.7235
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7412 - val_loss: 0.5598 - val_accuracy: 0.7249

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5598 - accuracy: 0.7249 - 435ms/epoch - 2ms/step
Loss: 0.5598486065864563, Accuracy: 0.7248979806900024

In [18]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

C:\Users\rontr\anaconda3\envs\dev\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(